package com.yx.po;

import java.io.Serializable;
import java.util.Date;

public class LendList implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lend_list.id
     *
     * @mbggenerated Sun Mar 10 22:17:10 EDT 2024
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lend_list.bookId
     *
     * @mbggenerated Sun Mar 10 22:17:10 EDT 2024
     */
    private Integer bookid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lend_list.readerId
     *
     * @mbggenerated Sun Mar 10 22:17:10 EDT 2024
     */
    private Integer readerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lend_list.lendDate
     *
     * @mbggenerated Sun Mar 10 22:17:10 EDT 2024
     */
    private Date lenddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lend_list.backDate
     *
     * @mbggenerated Sun Mar 10 22:17:10 EDT 2024
     */
    private Date backdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lend_list.backType
     *
     * @mbggenerated Sun Mar 10 22:17:10 EDT 2024
     */
    private Integer backtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lend_list.exceptRemarks
     *
     * @mbggenerated Sun Mar 10 22:17:10 EDT 2024
     */
    private String exceptremarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lend_list
     *
     * @mbggenerated Sun Mar 10 22:17:10 EDT 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lend_list.id
     *
     * @return the value of lend_list.id
     *
     * @mbggenerated Sun Mar 10 22:17:10 EDT 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lend_list.id
     *
     * @param id the value for lend_list.id
     *
     * @mbggenerated Sun Mar 10 22:17:10 EDT 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lend_list.bookId
     *
     * @return the value of lend_list.bookId
     *
     * @mbggenerated Sun Mar 10 22:17:10 EDT 2024
     */
    public Integer getBookid() {
        return bookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lend_list.bookId
     *
     * @param bookid the value for lend_list.bookId
     *
     * @mbggenerated Sun Mar 10 22:17:10 EDT 2024
     */
    public void setBookid(Integer bookid) {
        this.bookid = bookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lend_list.readerId
     *
     * @return the value of lend_list.readerId
     *
     * @mbggenerated Sun Mar 10 22:17:10 EDT 2024
     */
    public Integer getReaderid() {
        return readerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lend_list.readerId
     *
     * @param readerid the value for lend_list.readerId
     *
     * @mbggenerated Sun Mar 10 22:17:10 EDT 2024
     */
    public void setReaderid(Integer readerid) {
        this.readerid = readerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lend_list.lendDate
     *
     * @return the value of lend_list.lendDate
     *
     * @mbggenerated Sun Mar 10 22:17:10 EDT 2024
     */
    public Date getLenddate() {
        return lenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lend_list.lendDate
     *
     * @param lenddate the value for lend_list.lendDate
     *
     * @mbggenerated Sun Mar 10 22:17:10 EDT 2024
     */
    public void setLenddate(Date lenddate) {
        this.lenddate = lenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lend_list.backDate
     *
     * @return the value of lend_list.backDate
     *
     * @mbggenerated Sun Mar 10 22:17:10 EDT 2024
     */
    public Date getBackdate() {
        return backdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lend_list.backDate
     *
     * @param backdate the value for lend_list.backDate
     *
     * @mbggenerated Sun Mar 10 22:17:10 EDT 2024
     */
    public void setBackdate(Date backdate) {
        this.backdate = backdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lend_list.backType
     *
     * @return the value of lend_list.backType
     *
     * @mbggenerated Sun Mar 10 22:17:10 EDT 2024
     */
    public Integer getBacktype() {
        return backtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lend_list.backType
     *
     * @param backtype the value for lend_list.backType
     *
     * @mbggenerated Sun Mar 10 22:17:10 EDT 2024
     */
    public void setBacktype(Integer backtype) {
        this.backtype = backtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lend_list.exceptRemarks
     *
     * @return the value of lend_list.exceptRemarks
     *
     * @mbggenerated Sun Mar 10 22:17:10 EDT 2024
     */
    public String getExceptremarks() {
        return exceptremarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lend_list.exceptRemarks
     *
     * @param exceptremarks the value for lend_list.exceptRemarks
     *
     * @mbggenerated Sun Mar 10 22:17:10 EDT 2024
     */
    public void setExceptremarks(String exceptremarks) {
        this.exceptremarks = exceptremarks == null ? null : exceptremarks.trim();
    }
}