package com.yx.dao;

import com.yx.po.LendList;

public interface LendListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lend_list
     *
     * @mbggenerated Sun Mar 10 22:17:10 EDT 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lend_list
     *
     * @mbggenerated Sun Mar 10 22:17:10 EDT 2024
     */
    int insert(LendList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lend_list
     *
     * @mbggenerated Sun Mar 10 22:17:10 EDT 2024
     */
    int insertSelective(LendList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lend_list
     *
     * @mbggenerated Sun Mar 10 22:17:10 EDT 2024
     */
    LendList selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lend_list
     *
     * @mbggenerated Sun Mar 10 22:17:10 EDT 2024
     */
    int updateByPrimaryKeySelective(LendList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lend_list
     *
     * @mbggenerated Sun Mar 10 22:17:10 EDT 2024
     */
    int updateByPrimaryKey(LendList record);
}