package com.yx.dao;

import com.yx.po.Notice;

import java.util.List;

public interface NoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbggenerated Sun Mar 10 22:17:10 EDT 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbggenerated Sun Mar 10 22:17:10 EDT 2024
     */
    int insert(Notice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbggenerated Sun Mar 10 22:17:10 EDT 2024
     */
    int insertSelective(Notice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbggenerated Sun Mar 10 22:17:10 EDT 2024
     */
    Notice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbggenerated Sun Mar 10 22:17:10 EDT 2024
     */
    int updateByPrimaryKeySelective(Notice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbggenerated Sun Mar 10 22:17:10 EDT 2024
     */
    int updateByPrimaryKey(Notice record);

    /**
     * Rechercher toutes les informations sur l'annonce
     */
    List<Notice> queryNoticeAll(Notice notice);
}