package com.yx.dao;

import com.yx.po.TypeInfo;

public interface TypeInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_info
     *
     * @mbggenerated Sun Mar 10 22:17:10 EDT 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_info
     *
     * @mbggenerated Sun Mar 10 22:17:10 EDT 2024
     */
    int insert(TypeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_info
     *
     * @mbggenerated Sun Mar 10 22:17:10 EDT 2024
     */
    int insertSelective(TypeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_info
     *
     * @mbggenerated Sun Mar 10 22:17:10 EDT 2024
     */
    TypeInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_info
     *
     * @mbggenerated Sun Mar 10 22:17:10 EDT 2024
     */
    int updateByPrimaryKeySelective(TypeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_info
     *
     * @mbggenerated Sun Mar 10 22:17:10 EDT 2024
     */
    int updateByPrimaryKey(TypeInfo record);
}